# Generated by Django 4.2 on 2023-08-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="categories",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.categories",
            ),
        ),
    ]
