# Generated by Django 4.2 on 2023-08-08 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_article_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="categories",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="api.categories",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
