# Generated by Django 4.2 on 2023-08-08 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_article_categories_alter_article_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="categories",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="api.categories",
            ),
        ),
    ]
