# Generated by Django 4.2.4 on 2023-09-20 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_article_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="categories",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="api.categories",
            ),
        ),
    ]
