# Generated by Django 4.2.4 on 2023-09-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_article_author_alter_article_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
