# Generated by Django 4.2.4 on 2023-09-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_article_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cover_img",
            field=models.ImageField(blank=True, null=True, upload_to="articles_cover"),
        ),
    ]
